export const INITIATE_STATE = "INITIATE_STATE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const INCREASE_CURRENT_PAGE = "INCREASE_CURRENT_PAGE";
export const DECREASE_CURRENT_PAGE = "DECREASE_CURRENT_PAGE";
export const SET_NUMBER_OF_PAGES = "SET_NUMBER_OF_PAGES";
export const SORT_COLUMN = "SORT_COLUMN";
export const SET_FILTER_SEARCH = "SET_FILTER_SEARCH"
