export const INCREASE_CURRENT_PAGE = "INCREASE_CURRENT_PAGE";
export const DECREASE_CURRENT_PAGE = "DECREASE_CURRENT_PAGE";
export const SET_NUMBER_OF_LIGN_TO_DISPLAY = "SET_NUMBER_OF_LIGN_TO_DISPLAY";
